--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ChampOfGames/NotesUI
build-by-default: true
branches:
- master
projects:
  NotesUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3    
...
